# Ding-plugin 默认配置文件


enableDingAdapter: true

dingdingAccounts:
  - accountId: ""              # 唯一账号标识符（必填）
    clientId: "" # 钉钉AppKey
    clientSecret: "" # 钉钉AppSecret
    webhook: "https://oapi.dingtalk.com/robot/sendBySession?session="
    debug: false
